sonar.projectKey=hrms
sonar.organization=equest
sonar.host.url=https://sonar.equest.solutions
sonar.token=${env.SONAR_TOKEN}

# Scan both frontend and backend
sonar.sources=frontend-hrms,backend-hrms

# Optional: explicitly set language roots if needed
sonar.javascript.lcov.reportPaths=frontend-hrms/coverage/lcov.info
sonar.nodejs.executable=/usr/bin/node