sonar.projectKey=hrms
sonar.host.url=https://sonar.equest.solutions
sonar.token=${env.SONAR_TOKEN}

# Scan both frontend and backend
sonar.sources=frontend-hrms,backend-hrms

# Optional: explicitly set SCM provider
sonar.scm.provider=git
