# Root project
sonar.projectKey=hrms
sonar.projectName=HRMS
sonar.host.url=https://sonar.equest.solutions
sonar.token=${env.SONAR_TOKEN}

# Define modules
sonar.modules=frontend-hrms,backend-hrms

# Frontend module
frontend-hrms.sonar.projectName=HRMS Frontend
frontend-hrms.sonar.sources=frontend-hrms/src
frontend-hrms.sonar.language=js

# Backend module
backend-hrms.sonar.projectName=HRMS Backend
backend-hrms.sonar.sources=backend-hrms
backend-hrms.sonar.language=js
